### ISSUE TITLE
I got this error.

### ISSUE THREAD

**Issue by DrOreo002** [TheBusyBiscuit/ExoticGarden#14]
Its works fine before, but after I load a map for my server and try to grow the Apple tree on my new map, it shows this on my server console. And my tree won't grow to Apple tree, but it grow to Oak tree.

Btw sorry for my bad English xD

This is the error logs :

14.07 16:03:58 [Server] ERROR Could not pass event StructureGrowEvent to ExoticGarden v1.6.3
14.07 16:03:58 [Server] INFO org.bukkit.event.EventException
14.07 16:03:58 [Server] INFO at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:306) ~[spigot-1.11.2.jar:git-Spigot-3fb9445-2b6c9f4]
14.07 16:03:58 [Server] INFO at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:62) ~[spigot-1.11.2.jar:git-Spigot-3fb9445-2b6c9f4]
14.07 16:03:58 [Server] INFO at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:502) [spigot-1.11.2.jar:git-Spigot-3fb9445-2b6c9f4]
14.07 16:03:58 [Server] INFO at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:487) [spigot-1.11.2.jar:git-Spigot-3fb9445-2b6c9f4]
14.07 16:03:58 [Server] INFO at net.minecraft.server.v1_11_R1.ItemStack.placeItem(ItemStack.java:177) [spigot-1.11.2.jar:git-Spigot-3fb9445-2b6c9f4]
14.07 16:03:58 [Server] INFO at net.minecraft.server.v1_11_R1.PlayerInteractManager.a(PlayerInteractManager.java:495) [spigot-1.11.2.jar:git-Spigot-3fb9445-2b6c9f4]
14.07 16:03:58 [Server] INFO at net.minecraft.server.v1_11_R1.PlayerConnection.a(PlayerConnection.java:913) [spigot-1.11.2.jar:git-Spigot-3fb9445-2b6c9f4]
14.07 16:03:58 [Server] INFO at net.minecraft.server.v1_11_R1.PacketPlayInUseItem.a(PacketPlayInUseItem.java:37) [spigot-1.11.2.jar:git-Spigot-3fb9445-2b6c9f4]
14.07 16:03:58 [Server] INFO at net.minecraft.server.v1_11_R1.PacketPlayInUseItem.a(PacketPlayInUseItem.java:1) [spigot-1.11.2.jar:git-Spigot-3fb9445-2b6c9f4]
14.07 16:03:58 [Server] INFO at net.minecraft.server.v1_11_R1.PlayerConnectionUtils$1.run(SourceFile:13) [spigot-1.11.2.jar:git-Spigot-3fb9445-2b6c9f4]
14.07 16:03:58 [Server] INFO at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) [?:1.8.0_131]
14.07 16:03:58 [Server] INFO at java.util.concurrent.FutureTask.run(FutureTask.java:266) [?:1.8.0_131]
14.07 16:03:58 [Server] INFO at net.minecraft.server.v1_11_R1.SystemUtils.a(SourceFile:46) [spigot-1.11.2.jar:git-Spigot-3fb9445-2b6c9f4]
14.07 16:03:58 [Server] INFO at net.minecraft.server.v1_11_R1.MinecraftServer.D(MinecraftServer.java:747) [spigot-1.11.2.jar:git-Spigot-3fb9445-2b6c9f4]
14.07 16:03:58 [Server] INFO at net.minecraft.server.v1_11_R1.DedicatedServer.D(DedicatedServer.java:399) [spigot-1.11.2.jar:git-Spigot-3fb9445-2b6c9f4]
14.07 16:03:58 [Server] INFO at net.minecraft.server.v1_11_R1.MinecraftServer.C(MinecraftServer.java:678) [spigot-1.11.2.jar:git-Spigot-3fb9445-2b6c9f4]
14.07 16:03:58 [Server] INFO at net.minecraft.server.v1_11_R1.MinecraftServer.run(MinecraftServer.java:576) [spigot-1.11.2.jar:git-Spigot-3fb9445-2b6c9f4]
14.07 16:03:58 [Server] INFO at java.lang.Thread.run(Thread.java:748) [?:1.8.0_131]
14.07 16:03:58 [Server] INFO Caused by: java.lang.NoSuchMethodError: org.jnbt.NBTInputStream.readTag()Lorg/jnbt/Tag;
14.07 16:03:58 [Server] INFO at me.mrCookieSlime.ExoticGarden.Schematic.loadSchematic(Schematic.java:168) ~[?:?]
14.07 16:03:58 [Server] INFO at me.mrCookieSlime.ExoticGarden.Tree.getSchematic(Tree.java:27) ~[?:?]
14.07 16:03:58 [Server] INFO at me.mrCookieSlime.ExoticGarden.Schematic.pasteSchematic(Schematic.java:116) ~[?:?]
14.07 16:03:58 [Server] INFO at me.mrCookieSlime.ExoticGarden.PlantsListener.onGrow(PlantsListener.java:54) ~[?:?]
14.07 16:03:58 [Server] INFO at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_131]
14.07 16:03:58 [Server] INFO at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_131]
14.07 16:03:58 [Server] INFO at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_131]
14.07 16:03:58 [Server] INFO at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_131]
14.07 16:03:58 [Server] INFO at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:302) ~[spigot-1.11.2.jar:git-Spigot-3fb9445-2b6c9f4]
14.07 16:03:58 [Server] INFO ... 17 more

**Comment by DrOreo002** [comment]
can someone help me pls?

**Comment by yariplus** [comment]
This error is due to another plugin defining the package `org.jnbt`, likely RedProtect.

The package `org.jnbt` needs to be renamed to something less generic or shaded.

I opened a [similar issue](https://github.com/FabioZumbi12/RedProtect/issues/196) on RedProtect.

**Comment by SoSeDiK** [comment]
This was fixed and can be closed now.

**Comment by yariplus** [comment]
RedProtect shaded their package, but the issue is not fixed.

Crash will still occur with any plugin that defines `org.jnbt`

**Comment by SoSeDiK** [comment]
Oh, okay. I'll see into this.
