### ISSUE TITLE
Bonemealing Plants Cause them to to move down a block, therefor breaking the block underneath it.

### ISSUE THREAD

**Issue by NickReagan** [TheBusyBiscuit/ExoticGarden#247]
Originally Reported on Discord; https://discord.com/channels/565557184348422174/565612454613090334/1000540693812494416

If you need anything else from me my Discord ID is; 168423441853186051

It does not seem as if other plugins/add-ons effect this issue as this was on an isolated server as shown below.
Proof and Versions;
![eg-bug-test-server](https://user-images.githubusercontent.com/52389274/181582789-52bbc3fd-4055-4a1c-8c21-bfeea302f3df.gif)

**Comment by AquawaNya** [comment]
Even Bedrocks, It can broke bedrocks!!!!!!

**Comment by AquawaNya** [comment]
And could broke blocks inside Residence

**Comment by galacticwarrior9** [comment]
Can confirm. Only an issue for double plants.

**Comment by SrMonsterYT** [comment]
with me the same thing is possible to break bedrock

video -> https://youtu.be/OOak00UIEa0

no console errors

image-> https://prnt.sc/kPBpd48NO7Cj

**Comment by JasperChaseTOQ** [comment]
does this only happen when bone mealed or whenever they grow?

**Comment by SrMonsterYT** [comment]
> does this only happen when bone mealed or whenever they grow?

when you grow up watch the video please.

**Comment by NickReagan** [comment]
> does this only happen when bone mealed or whenever they grow?

Only when bonemealed.

**Comment by AquawaNya** [comment]
I may know why it move down and down when mealed
double sound **Effect.STEP_SOUND**(in ExoticGarden.java:450) played.
Example of tea_leaf
First sound means turn **slimefun_id** from **tea_leaf_sapling** to **tea_leaf**, but it is **still** **oak_sapling**. and up side block slimefun_id from none to tea_leaf too. It's strange.
next sound because only down side is clickable. so players click downside and harvestPlant check Tags is not plant block so it replace it to air and down a block to plant.
(em. my English is not good...sorry)

**Comment by SrMonsterYT** [comment]
when will this be resolved? people are abusing this, to break bedrock

**Comment by NickReagan** [comment]
> when will this be resolved? people are abusing this, to break bedrock

I recommend disabling Exotic Garden until a patch update is released due to the game breaking aspect. Simply make a folder called "_disabled" in your plugins folder and put it in there, or just delete the JAR.

**Comment by SrMonsterYT** [comment]
> 

ok thanks, it makes me sad how addons are so abandoned like this.

**Comment by ZEROOblivious** [comment]
Confirmed having this issue on 1.19.2. 
I believe this is a 1.19.x bug as this never happened on 1.18.2.

**Comment by SrMonsterYT** [comment]
> 

everyone is asking him to fix it and so far we don't have a fix update :( :( 

please fix it soon players are abusing the bug

**Comment by garathnor** [comment]
https://www.youtube.com/watch?v=gabJ23dBeeM

dont think this issue is fixed

**Comment by JasperChaseTOQ** [comment]
yup the issue is still open so its not fixed

**Comment by NBWNeo** [comment]
Yea, this issue is still a problem im a player on a server, and this thing breaks ANYTHING bedrock end portal frames HELL IT BREAKS THE PORTAL in the end or end portal.

**Comment by NBWNeo** [comment]
https://youtu.be/XO4v6C6oRZI

litterally broke a entire chunk with this bug.

**Comment by garathnor** [comment]
its cute you all think breaking bedrock is the scary part of this issue, when my video shows the saplings being duplicated, so ya know, 1 netherite/diamond/emerald plant into 100 inside an hour, break your economy much?

**Comment by NBWNeo** [comment]
I never had a problem of it being duped. I cant find a way for that, only breaking any blocks

**Comment by garathnor** [comment]
literally just watch my video, its easy

**Comment by NBWNeo** [comment]
Ok, wow it is that easy. I just did it and damnn that is so stupid. Right now I am trying to figure out a way to auto harvest these plants to do multiple plants at once. sadly cant find a way. this is my setup rn

![image](https://user-images.githubusercontent.com/114778068/193375786-7bbaac6d-d784-41d1-a2c1-485355cc0983.png)
![image](https://user-images.githubusercontent.com/114778068/193375793-678a99c9-aab2-45ce-b094-ef3cfb6685a4.png)

**Comment by asd969704376** [comment]
when will this bug be fixed i lost the way to fast get diamond(carbon) in early time
